### PR TITLE
feat: new paradigm for cycle – `State` + `Delta`

### PR DESCRIPTION
**Pull request by hollandjg**
Add a new interface for theorists, experimentalists, experiment_runners, cycles and pipelines.

The new paradigm works like this:
- The cycle state $S$ is represented as $$S_n = S_{0} + \sum^n_{i=1}  \Delta S_{i}$$ – the starting state plus some deltas.
- Each cycle step (theorist, experimentalist, experiment_runner) is defined as $$f(\mathrm{arguments}) \rightarrow \Delta S_{i}$$
- There is a helper interface $g$ which maps $$g\left[f(\mathrm{arguments}) \rightarrow \Delta S_{i}\right] \rightarrow \left[ f^\prime(S_i) \rightarrow S_{i+1}\right]$$

The full cycle can then be flexibly defined using completely boring python notation like:
```python
experimentalist = experimentalist_from_pipeline(random_experimentalist)
experiment_runner = experiment_runner_from_x_to_y_function(lambda x: x**2 - 2x + 3)
theorist = theorist_from_estimator(DARTSRegressor())

s_ = State(variables=VariableCollection(...))
for i in range(10):
    s_ = experimentalist(s_)
    s_ = experiment_runner(s_)
    s_ = theorist(s_)

print(s_)
```
... simplifying or removing the need for a lot of the additional workflow classes (like Controller, Cycle, SimpleCycle).

Includes initial support for pandas DataFrames.

Todos:
- [x] Work out how to handle inner functions which need an argument (like "n_samples_each_cycle" in the experimentalist, or "some_temperature") which doesn't just fail if that field name isn't available on the state
- [x] Convert the existing example which uses series into something which uses dataframes
- [x] Undo additional file changes

Make new issues and/or PRs for:
- [x] Add support for more datatypes – np.dataframes AutoResearch/autora-core#22 
- [x] Change names of functions to be more generic (@younesStrittmatter – your idea) AutoResearch/autora-core#23

Don't dos:
- Add a Controller (in the old sense) which uses this setup – can it be simpler than the old one? Can we do the same thing as all the existing cases, like have a history record too?

### CODE REVIEW

**Comment by musslick** [comment]
From what I can tell, this looks quite promising! Eager to discuss more!

**Comment by younesStrittmatter** [comment]
I made changes to the jupiter notebook and created a pull-request to this branch. The rest seems very good and I would merge this into main as the first version and keep extending it.
One additional thing, we could provide standard state with VariableCollection, Params, conditions, experimental_data, 
 and models (just as the Snapshot in the Tutoraial) that a user can directly instantiate without having to define the class? I think that most users will likely only use that version.

**Comment by hollandjg** [comment]
@younesStrittmatter @benwandrew @musslick: should we jump ahead and just make the `state` part of `autora-core`?

**Comment by hollandjg** [comment]
> @younesStrittmatter @benwandrew @musslick: should we jump ahead and just make the `state` part of `autora-core`?

Let's do that in three steps if we do it: 
1. merge this PR AutoResearch/autora-workflow#17 
2. restructure as in AutoResearch/autora-workflow#28 so that you import from `autora.state`.
3. release a new version of autora-workflow so we can get going with the docs.
5. next week: do a separate PR to merge the code into aurora-core and remove the `autora.state` namespace sub package here.

**Comment by benwandrew** [comment]
that sounds like a solid plan to me. i am making my way through this PR, and although my review hasn't been extremely comprehensive (yet), all looks good.

**Review by benwandrew — APPROVED** [review]
:rocket:

**Pull request merged**
